name: Coverage

on:
  push:
    branches:
      - '1.*'
  pull_request:
    types:
      - synchronize
      - opened
      - edited
      - reopened

jobs:
  coverage:
    runs-on: ubuntu-latest

    env:
      PHP_VERSION: '8.2'
      LARAVEL_VERSION: '^11.0'
      TESTBENCH_VERSION: '^9.0'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select PHP version
        uses: shivammathur/setup-php@v2
        with:
          php-version: '${{ env.PHP_VERSION }}'
          extensions: mbstring, pdo_sqlite, fileinfo, gd
          coverage: pcov
          tools: composer:v2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16.x'
          cache: npm

      - name: Configure Laravel test environment
        run: |
          composer require --dev \
            "laravel/framework:${{ env.LARAVEL_VERSION }}" \
            "orchestra/testbench:${{ env.TESTBENCH_VERSION }}" \
            --no-update \
            --no-interaction \
            --no-ansi

      - name: Install Composer dependencies
        run: composer update --prefer-dist --no-interaction --no-progress --no-ansi --with-all-dependencies

      - name: Show installed versions
        run: |
          composer show laravel/framework
          composer show orchestra/testbench

      - name: Generate vendor symlink
        run: ./vendor/bin/testbench

      - name: Install NPM dependencies
        run: npm ci

      - name: Compile Assets
        run: npm run prod

      - name: Run tests for coverage
        run: php -d pcov.enabled=1 ./vendor/bin/phpunit --coverage-clover=coverage.xml

      - name: Upload coverage
        run: bash <(curl -s https://codecov.io/bash)